version: '3'

services:
 control:
  image: adminer
  depends_on:
   - db_postgresql
  ports:
   - "80:8080"
  restart: always

 db_postgresql:
  image: postgres
  container_name: db_postgres
  restart: always
  ports:
   - "5432:5432"
  volumes:
   - db_postgres_vol:/var/lib/postgresql/data
  environment: 
   POSTGRES_PASSWORD: superRootPassword
   POSTGRES_USER: lucasca95
   POSTGRES_PASSWORD: admin
   POSTGRES_DB: db

 # db_mysql:
 #  image: mysql
 #  command: --default-authentication-plugin=mysql_native_password
 #  container_name: db_mysql
 #  restart: always
 #  ports:
 #   - "3306:3306"
 #  volumes:
 #   - db_mysql_vol:/var/lib/mysql
 #  environment: 
 #   MYSQL_ROOT_PASSWORD: superRootPassword
 #   MYSQL_USER: lucasca95
 #   MYSQL_PASSWORD: admin
 #   MYSQL_DATABASE: db
                
volumes:
 db_mysql_vol:
 db_postgres_vol:
        
# javaspring_web:
    #     build:
    #         context: .
    #         args:
    #             JAR_FILE: target/webapp-0.0.1-SNAPSHOT.jar
    #     image: javaspring_web
    #     container_name: javaspring_web
    #     ports:
    #         - "80:8080"
    #     volumes:
    #         - ./webapp:/javaspring_web
